### ISSUE TITLE
Understanding message>>message composition>>Unary > Binary > Keywords

### ISSUE THREAD

**Issue by gocko** [SquareBracketAssociates/PharoByExample80#11]
"Unary messages are sent first, then binary messages, and finally, keyword messages.
We also ...
 Unary messages are sent first, then binary messages, and finally keyword based messages. ==Unary > Binary > Keyword==..."

These are the 2nd and the 3rdtime this is repeated: "Unary messages are sent first, then binary messages, and finally, keyword messages". The first time was a few paragraphs before. Is that intentionally?

**Comment by Ducasse** [comment]
I will check I imagine that this should be in summary like

@@important

**Comment by gocko** [comment]
I think it is ok now...
